(*
Defs.inc
--------
Begin: 2009/08/12
Last revision: $Date: 2009-08-13 17:23:33 $ $Author: areeves $
Version: $Revision: 1.2 $
Project: Demo application for the Delphi wrapper for the Proj.4 Cartographic Projections library
Website: http://www.naadsm.org/opensource
Author: Aaron Reeves <Aaron.Reeves@colostate.edu>
--------------------------------------------------
Copyright (C) 2009 Animal Population Health Institute, Colorado State University

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General
Public License as published by the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
*)

// Define the following symbol to display and use the debugging window.
//{$DEFINE DEBUG}